apiVersion: apps/v1
kind: Deployment
metadata:
  name: altoroj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: altoroj
  template:
    metadata:
      labels:
        app: altoroj
    spec:
      containers:
        - image: docker.io/rodneylive/altoroj:1.0
          name: altoroj
          ports:
            - containerPort: 8080
