apiVersion: apps/v1
kind: Deployment
metadata:
  name: altoroj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: altoroj
  template:
    metadata:
      labels:
        app: altoroj
    spec:
      containers:
        - image: 192.168.69.115:5443/altoroj:test
          name: altoroj
          ports:
            - containerPort: 8080
