keycloak.url=http://localhost:8085
keycloak.realm=myrealm
keycloak.clientId=altoro
keycloak.clientSecret=ZFjUh4SGWLBj7OzuTb6H2ZrM9U3P9492JcloaoFvvSNIlfmRyQT3oTpLw5bbrj8XTmnVkx6Vywh1E09gErNByO
keycloak.redirectUri=http://localhost:8088/altoromutual/oidc/callback
keycloak.postLogoutRedirectUri=http://localhost:8088/altoromutual/index.jsp
