keycloak.url=http://localhost:8085
keycloak.realm=myrealm
keycloak.clientId=altoro
keycloak.redirectUri=http://localhost:8088/altoromutual/oidc/callback
keycloak.postLogoutRedirectUri=http://localhost:8088/altoromutual/index.jsp
