name: "HCL AppScan SAST"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.9
        with:
          asoc_key: ${{secrets.APPSCAN_KEY}}
          asoc_secret: ${{secrets.APPSCAN_SECRET}}
          application_id: 87f7367f-698c-409f-99a7-aaa7d03f7d3b
          static_analysis_only: true
          wait_for_analysis: true
          acceptssl: false
          scan_build_outputs: true
