name: "HCL AppScan SAST"
on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.1.2
        with:
          asoc_key: ${{secrets.APPSCAN_KEY}}
          asoc_secret: ${{secrets.APPSCAN_SECRET}}
          application_id: 8a9bb7c7-892d-4cf0-bfda-43527a100fdc
          static_analysis_only: true
          #open_source_only: true
          wait_for_analysis: true
